resolver: lts-15.5
packages:
- ./yesod-core
- ./yesod-static
- ./yesod-persistent
- ./yesod-newsfeed
- ./yesod-form
- ./yesod-form-multi
- ./yesod-auth
- ./yesod-auth-oauth
- ./yesod-sitemap
- ./yesod-test
- ./yesod-bin
- ./yesod
- ./yesod-eventsource
- ./yesod-websockets
- ./persistent/persistent
- ./persistent/persistent-template
- ./persistent/persistent-sqlite

extra-deps:
- resourcet-pool-0.1.0.0
